---
# handlers file for netdata
- name: Reload systemd netdata
  systemd:
    name: "netdata"
    daemon_reload: true
  become: true

- name: Restart netdata
  service:
    name: "netdata"
    state: "restarted"
    enabled: true
    sleep: 10
  become: true

- name: Start netdata
  service:
    name: "netdata"
    state: "started"
    enabled: true
  become: true

- name: Stop netdata
  service:
    name: "netdata"
    state: "stopped"
    enabled: true
  become: true
