---
  - name: Converge
    hosts: all
    vars:
      netdata_epel_setup: "{{ ansible_hostname == 'centos7' }}"
      netdata_git_version_tag: v1.35.0
    tasks:
      - name: "Include buluma.netdata"
        ansible.builtin.include_role:
          name: "buluma.netdata"
